require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CastsController do

  # This should return the minimal set of attributes required to create a valid
  # Cast. As you add validations to Cast, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "match_type" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CastsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all casts as @casts" do
      cast = Cast.create! valid_attributes
      get :index, {}, valid_session
      assigns(:casts).should eq([cast])
    end
  end

  describe "GET show" do
    it "assigns the requested cast as @cast" do
      cast = Cast.create! valid_attributes
      get :show, {:id => cast.to_param}, valid_session
      assigns(:cast).should eq(cast)
    end
  end

  describe "GET new" do
    it "assigns a new cast as @cast" do
      get :new, {}, valid_session
      assigns(:cast).should be_a_new(Cast)
    end
  end

  describe "GET edit" do
    it "assigns the requested cast as @cast" do
      cast = Cast.create! valid_attributes
      get :edit, {:id => cast.to_param}, valid_session
      assigns(:cast).should eq(cast)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Cast" do
        expect {
          post :create, {:cast => valid_attributes}, valid_session
        }.to change(Cast, :count).by(1)
      end

      it "assigns a newly created cast as @cast" do
        post :create, {:cast => valid_attributes}, valid_session
        assigns(:cast).should be_a(Cast)
        assigns(:cast).should be_persisted
      end

      it "redirects to the created cast" do
        post :create, {:cast => valid_attributes}, valid_session
        response.should redirect_to(Cast.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved cast as @cast" do
        # Trigger the behavior that occurs when invalid params are submitted
        Cast.any_instance.stub(:save).and_return(false)
        post :create, {:cast => { "match_type" => "invalid value" }}, valid_session
        assigns(:cast).should be_a_new(Cast)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Cast.any_instance.stub(:save).and_return(false)
        post :create, {:cast => { "match_type" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested cast" do
        cast = Cast.create! valid_attributes
        # Assuming there are no other casts in the database, this
        # specifies that the Cast created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Cast.any_instance.should_receive(:update).with({ "match_type" => "MyString" })
        put :update, {:id => cast.to_param, :cast => { "match_type" => "MyString" }}, valid_session
      end

      it "assigns the requested cast as @cast" do
        cast = Cast.create! valid_attributes
        put :update, {:id => cast.to_param, :cast => valid_attributes}, valid_session
        assigns(:cast).should eq(cast)
      end

      it "redirects to the cast" do
        cast = Cast.create! valid_attributes
        put :update, {:id => cast.to_param, :cast => valid_attributes}, valid_session
        response.should redirect_to(cast)
      end
    end

    describe "with invalid params" do
      it "assigns the cast as @cast" do
        cast = Cast.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Cast.any_instance.stub(:save).and_return(false)
        put :update, {:id => cast.to_param, :cast => { "match_type" => "invalid value" }}, valid_session
        assigns(:cast).should eq(cast)
      end

      it "re-renders the 'edit' template" do
        cast = Cast.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Cast.any_instance.stub(:save).and_return(false)
        put :update, {:id => cast.to_param, :cast => { "match_type" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested cast" do
      cast = Cast.create! valid_attributes
      expect {
        delete :destroy, {:id => cast.to_param}, valid_session
      }.to change(Cast, :count).by(-1)
    end

    it "redirects to the casts list" do
      cast = Cast.create! valid_attributes
      delete :destroy, {:id => cast.to_param}, valid_session
      response.should redirect_to(casts_url)
    end
  end

end
